export const USERS = [
  {
    id: 'u1',
    firstNamename: 'Keerthi',
    LastName:'Bali',
    Email:'keerthi.bali2004@gmail.com',
    Age:21,
    Gender:'female',
    dob:19-9-2004,
    avatar: 'user-1.jpg',
  },
  {
    id: 'u2',
    firstNamename: 'Satya',
    LastName:'mamidi',
    Email:'satya.2008.@.gmail.com',
    Age:18,
    Gender:'female',
    dob:21-7-2008,
    avatar: 'user-2.jpg',
  },
  {
    id: 'u3',
    firstNamename: 'Suhash',
    LastName:'kolli',
    Email:'suha2016.@.gmail.com',
    Age:8,
    Gender:'male',
    dob:15-9-2016,
    avatar: 'user-3.jpg',
  },
  {
    id: 'u4',
    firstNamename: 'Leo',
    LastName:'komarapu',
    Email:'Leokomarapu.@.gmail.com',
    Age:21,
    Gender:'male',
    dob:19-12-2004,
    avatar: 'user-4.jpg',
  },
  {
    id: 'u5',
    firstNamename: 'Gayatri',
    LastName:'thamineni',
    Email:'gayu-2006@gmail.com',
    Age:19,
    Gender:'female',
    dob:27-7-2006,
    avatar: 'user-1.jpg',
  },
  {
    id: 'u6',
    firstNamename: 'Chandu',
    LastName:'uralapu',
    Email:'chandu.2005@gmail.com',
    Age:20,
    Gender:'male',
    dob:9-9-2005,
    avatar: 'user-5.jpg',
  },
   {
    id: 'u6',
    firstNamename: 'Harini',
    LastName:'Killamamasetti',
    Email:'harini.srtti89@gmail.com',
    Age:17,
    Gender:'female',
    dob:8-3-2007,
    avatar: 'user-2.jpg',
  },
   {
    id: 'u6',
    firstNamename: 'Bigil',
    LastName:'Vj',
    Email:'thala.vj04@gmail.com',
    Age:49,
    Gender:'male',
    dob:21-6-1986,
    avatar: 'user-4.jpg',
  },
   {
    id: 'u6',
    firstNamename: 'Rishita',
    LastName:'pocham',
    Email:'rushi.pocham@gmail.com',
    Age:25,
    Gender:'female',
    dob:6-2-2001,
    avatar: 'user-1.jpg',
  },
   {
    id: 'u6',
    firstNamename: 'Komal',
    LastName:'Meesala',
    Email:'komal.meesala457@gmail.com',
    Age:21,
    Gender:'female',
    dob:21-7-2003,
    avatar: 'user-4.jpg',
  },

];